include $(GOROOT)/src/Make.inc

TARG=draw2d.googlecode.com/svn/trunk/draw2d/src/pkg/draw2d
GOFILES=\
	arc.go\
	curves.go\
	draw2d.go\
	math.go\
	path.go\
	transform.go\
	dasher.go\
	demux_converter.go\
	font.go\
	path_adder.go\
	path_converter.go\
	path_storage.go\
	stroker.go\

include $(GOROOT)/src/Make.pkg
