include $(GOROOT)/src/Make.inc

TARG=draw2d.googlecode.com/hg/postscript
GOFILES=operators_array.go\
	operators_dictionary.go\
	operators_misc.go\
	procedure.go\
	interpreter.go\
	operators_conflict.go\
	operators_graphics.go\
	operators_relational.go\
	scanner.go\
	operators.go\
	operators_control.go\
	operators_math.go\
	operators_stack.go\

include $(GOROOT)/src/Make.pkg
