include $(GOROOT)/src/Make.inc

TARG=draw2d.googlecode.com/hg/draw2d
GOFILES=\
	arc.go\
	curves.go\
	draw2d.go\
	math.go\
	path.go\
	transform.go\
	dasher.go\
	demux_converter.go\
	font.go\
	path_adder.go\
	path_converter.go\
	path_storage.go\
	stroker.go\
	advanced_path.go\
	vertex2d.go\
	gc.go\
	paint.go\

include $(GOROOT)/src/Make.pkg
