include $(GOROOT)/src/Make.inc

TARG=code.google.com/p/draw2d/draw2d
GOFILES=\
	draw2d.go\
	arc.go\
	curves.go\
	image.go\
	math.go\
	path.go\
	transform.go\
	dasher.go\
	demux_converter.go\
	font.go\
	path_adder.go\
	path_converter.go\
	path_storage.go\
	stroker.go\
	advanced_path.go\
	vertex2d.go\
	gc.go\
	paint.go\
	stack_gc.go\
	rgba_interpolation.go\

include $(GOROOT)/src/Make.pkg
