include $(GOROOT)/src/Make.inc

TARG=draw2d.googlecode.com/hg/draw2d/raster
GOFILES=\
	line.go\
	polygon.go\
	coverage_table.go\
	fillerAA.go\
	fixed_point.go
	

include $(GOROOT)/src/Make.pkg
