include $(GOROOT)/src/Make.inc

TARG=postscript-go.googlecode.com/svn/trunk/postscript-go/src/pkg/postscript
GOFILES=\
	interpreter.go\
	operators.go\
	operators_control.go\
	operators_dictionary.go\
	operators_graphics.go\
	operators_math.go\
	operators_relational.go\
	operators_stack.go\
	procedure.go\
	scanner.go\

include $(GOROOT)/src/Make.pkg
